version: '3.8'

services:
  database:
    image: mysql:8.4
    container_name: moodle_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      # Automatischer Import der alten Datenbank von 3.10
      - ./moodledump.sql:/docker-entrypoint-initdb.d/moodledump.sql:ro
    networks:
      - moodle_net

  moodle:
    build: .
    container_name: moodle_web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
    volumes:
      - ./moodledata:/var/www/moodledata
    networks:
      - moodle_net

volumes:
  dbdata:

networks:
  moodle_net:
    driver: bridge